dependencies {
    implementation project(':backend:domain')

    implementation 'org.springframework:spring-context'

    implementation "ai.djl:api:${djlVersion}"

    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testImplementation 'org.mockito:mockito-core:5.14.2'
}