spring:
  application:
    name: mindweave-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/mindweave_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD}
