spring:
  application:
    name: mindweave-backend

  # Configurare PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/mindweave_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Configurare Flyway pentru migr?ri automate
  flyway:
    url: jdbc:postgresql://localhost:5432/mindweave_db
    user: postgres
    password: postgres
    baseline-on-migrate: true

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: mindweave
